baseURL = 'https://yirik.org/'
languageCode = 'en-us'
title = 'ཡིག་རིགས་དང་ཡིག་གཟུགས། Tibetan Scriptology'
#theme = ["PaperMod"]
theme = ["PaperMod"]

[params]
  description = "Tibetan Scriptology"
  defaultTheme = "light"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = true

[params.homeInfoParams]
  Title = 'ཡིག་རིགས་དང་ཡིག་གཟུགས། Tibetan Scriptology'
  Content = 'Resources on the Tibetan script: paleography, fonts, technology'